whitelist_rules:

# 상시 활성화 (자동)
  - attributes # opt-in
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - closure_spacing # opt-in
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline # opt-in
  - control_statement
  - cyclomatic_complexity # opt-in
  - discarded_notification_center_observer
  - dynamic_inline
  - empty_count # opt-in
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init # opt-in
  - file_length
  - first_where # opt-in
  - for_where
  - force_cast
  - force_try
  - force_unwrapping # opt-in
#  - function_body_length
  - function_parameter_count
  - generic_type_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
#  - line_length
  - mark
  - multiline_parameters
  - nesting
  - notification_center_detachment
  - number_separator # opt-in
 # - object_literal # opt-in
  - opening_brace
  - operator_usage_whitespace # opt-in
  - operator_whitespace
  - overridden_super_call # opt-in
  - private_unit_test
  - prohibited_super_call # opt-in
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing # opt-in
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - statement_position
  - syntactic_sugar
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - weak_delegate

# 수시 점검 (수동)
#  - file_header # opt-in
  - private_outlet # opt-in
  - todo


# 검사할 파일경로
included:
  - ../WhySoSerious
  
excluded:
  - Carthage
  - Pods

# 룰별 커스터마이징
function_body_length:
   warning: 60

file_length:
  warning: 500

type_body_length:
  warning: 300
  
line_length:
  ignores_urls: true
  warning: 300

cyclomatic_complexity:
  warning: 30
  error: 30

large_tuple:
  warning: 3


force_cast:
  severity: error

force_unwrapping:
  severity: error

class_delegate_protocol:
  severity: error

closure_spacing:
  severity: error

compiler_protocol_init:
  severity: error

control_statement:
  severity: error

implicit_getter:
  severity: error

operator_whitespace:
  severity: error

redundant_string_enum_value:
  severity: error

syntactic_sugar:
  severity: error

unused_enumerated:
  severity: error

unused_optional_binding: 
  severity: error

vertical_parameter_alignment:
  severity: error

weak_delegate:
  severity: error
